version: '3.4'

services:
  Vulnerable-Web-Application:
    environment:
      - CONTRAST__SERVER__NAME=Vulnerable-Web-Application-prod
      - CONTRAST__SERVER__ENVIRONMENT=Production 
      - CONTRAST__ASSESS__ENABLE=false
      - CONTRAST__PROTECT__ENABLE=true
