version: "3.4"

services:
  petclinic:
    image: smithst987/Vulnerable-Web-Application
    container_name: Vulnerable-Web-Application
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./contrast_security.yaml:/app/Vulnerable-Web-Application/contrast_security.yaml
    environment:
      - CONTRAST_CONFIG_PATH=/app/Vulnerable-Web-Application/contrast_security.yaml
      - CONTRAST__ENABLE=TRUE
      - CONTRAST__AGENT__JAVA__STANDALONE__APP__NAME=Vulnerable-Web-Application
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS, contact=steve.smith@contrastsecurity.com
    ports:
      - "8686:8080"
